### ISSUE TITLE
Release 1.4 causes ImportError

### ISSUE THREAD

**Issue by hvelarde** [reinout/z3c.recipe.usercrontab#6]
Problem does not happen with release 1.3:

``` python
project@project:~/buildout$ bin/buildout -N
Develop: '/home/project/buildout/.'
While:
  Installing.
  Getting section supervisor-cron.
  Initializing section supervisor-cron.
  Loading zc.buildout recipe entry z3c.recipe.usercrontab:default.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/project/buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1866, in main
    getattr(buildout, command)(args)
  File "/home/project/buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 509, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/project/buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1104, in __getitem__
    options._initialize()
  File "/home/project/buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1189, in _initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/project/buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1149, in _install_and_load
    req.project_name, group, entry)
  File "/home/project/buildout/eggs/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 318, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/project/buildout/eggs/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2221, in load_entry_point
    return ep.load()
  File "/home/project/buildout/eggs/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/project/buildout/eggs/z3c.recipe.usercrontab-1.4-py2.7.egg/z3c/recipe/usercrontab/__init__.py", line 12, in <module>
    from zc.buildout.buildout import bool_option
ImportError: cannot import name bool_option
```

**Comment by reinout** [comment]
You have a 1.7.1 buildout, that one is very old. The 1.6/1.7 release is one where they restructured buildout quite a lot, so it might very well be that some import is in a different place there.

The current buildout (2.x) is based off buildout 1.4.

Can you upgrade to a newer buildout? If not, you'll have to stay with 1.3 (there haven't been any big changes between 1.3 and 1.4, so you ought to be fine with 1.3).

**Comment by hvelarde** [comment]
ok, thanks! (@rodfersou, FYI)
